auto: true
paginate: 8
baseurl: /wiyt.github.io
pygments: true
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
kramdown:
  input: GFM
defaults:
  -
    scope:
      path: "blogs"
      type: "pages"
    values:
      layout: "default"
      author: "wiyt"
      category: "blogs"
  -
      scope:
      path: "opinion"
      type: "pages"
    values:
      layout: "default"
      author: "wiyt"
      category: "opinion"
