highlighter: pygments
# markdown: redcarpet
# redcarpet:
#   extensions:
#     - hard_wrap
#     - no_intra_emphasis
#     - autolink
#     - strikethrough
#     - fenced_code_blocks
# kramdown:
#   input: GFM
permalink: /:categories/:year/:month/:day/:title 
production_url : http://wiyt.github.io
